swagger: "2.0"
info:
  description: "API para ejercicios de Python"
  version: "1.0.0"
  title: "API Python"
  
host: "127.0.0.1:5000"
schemes: ["http"]

tags:
- name: "posts"
  description: "Acciones relacionadas con los posts"
- name: "comments"
  description: "Acciones relacionadas con los comentarios"

paths:
  /posts:
    get:
      tags:
      - "posts"
      summary: "Devuelve una lista con todos los posts"
      description: ""
      operationId: "getPosts"
      produces:
      - "application/json"
      responses:
        "200":
          description: "Petici贸n correcta"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Post"
        "400":
          description: "Error desconocido"
          schema:
            $ref: "#/definitions/Error"
          
    post:
      tags:
      - "posts"
      summary: "Crea un nuevo post"
      description: ""
      operationId: "addPost"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Los datos de un post"
        required: true
        schema:
          $ref: "#/definitions/NewPost"
      responses:
        "200":
          description: "OK"
          schema:
            $ref: "#/definitions/Post"
        "400":
          description: "Error desconocido"
          schema:
            $ref: "#/definitions/Error"
    
  /posts/{id}:
    get:
      tags:
      - "posts"
      summary: "Devuelve toda la insformaci贸n del post solicitaddo"
      description: ""
      operationId: "getPostsById"
      parameters:
      - name: "id"
        in: "path"
        description: "ID del post"
        required: true
        type: "integer"
        format: "int64"
      produces:
      - "application/json"
      responses:
        "200":
          description: "OK"
          schema:
            $ref: "#/definitions/Post"
        "400":
          description: "Error desconocido"
          schema:
            $ref: "#/definitions/Error"
    put:
      tags:
      - "posts"
      summary: "Modifica el post"
      description: ""
      operationId: "editPostsById"
      parameters:
      - name: "id"
        in: "path"
        description: "ID del post"
        required: true
        type: "integer"
        format: "int64"
      - in: "body"
        name: "body"
        description: "Los datos que se quieran modificar"
        required: true
        schema:
          $ref: "#/definitions/EditPost"
      produces:
      - "application/json"
      responses:
        "200":
          description: "OK"
          schema:
            $ref: "#/definitions/Post"
        "400":
          description: "Error desconocido"
          schema:
            $ref: "#/definitions/Error"
    delete:
      tags:
      - "posts"
      summary: "Elimina el post"
      description: ""
      operationId: "deletePostsById"
      parameters:
      - name: "id"
        in: "path"
        description: "ID del post"
        required: true
        type: "integer"
        format: "int64"
      produces:
      - "application/json"
      responses:
        "200":
          description: "OK"
        "400":
          description: "Error desconocido"
          schema:
            $ref: "#/definitions/Error"
  /comments:
    get:
      tags:
      - "comments"
      summary: "Devuelve una lista con todos los comentarios"
      description: ""
      operationId: "getComments"
      produces:
      - "application/json"
      responses:
        "200":
          description: "Petici贸n correcta"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Comment"
        "400":
          description: "Error desconocido"
          schema:
            $ref: "#/definitions/Error"
          
    post:
      tags:
      - "comments"
      summary: "Crea un nuevo comentario"
      description: ""
      operationId: "addComment"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Los datos de un post"
        required: true
        schema:
          $ref: "#/definitions/NewComment"
      responses:
        "200":
          description: "OK"
          schema:
            $ref: "#/definitions/Comment"
        "400":
          description: "Error desconocido"
          schema:
            $ref: "#/definitions/Error"
    
  /comments/{id}:
    get:
      tags:
      - "comments"
      summary: "Devuelve toda la insformaci贸n del comentario solicitaddo"
      description: ""
      operationId: "getCommentsById"
      parameters:
      - name: "id"
        in: "path"
        description: "ID del comentario"
        required: true
        type: "integer"
        format: "int64"
      produces:
      - "application/json"
      responses:
        "200":
          description: "OK"
          schema:
            $ref: "#/definitions/Comment"
        "400":
          description: "Error desconocido"
          schema:
            $ref: "#/definitions/Error"
    put:
      tags:
      - "comments"
      summary: "Modifica el comentario"
      description: ""
      operationId: "editCCommentsById"
      parameters:
      - name: "id"
        in: "path"
        description: "ID del comentario"
        required: true
        type: "integer"
        format: "int64"
      - in: "body"
        name: "body"
        description: "Los datos que se quieran modificar"
        required: true
        schema:
          $ref: "#/definitions/EditComment"
      produces:
      - "application/json"
      responses:
        "200":
          description: "OK"
          schema:
            $ref: "#/definitions/Comment"
        "400":
          description: "Error desconocido"
          schema:
            $ref: "#/definitions/Error"
    delete:
      tags:
      - "comments"
      summary: "Elimina el comentario"
      description: ""
      operationId: "deleteCommentsById"
      parameters:
      - name: "id"
        in: "path"
        description: "ID del comentario"
        required: true
        type: "integer"
        format: "int64"
      produces:
      - "application/json"
      responses:
        "200":
          description: "OK"
        "400":
          description: "Error desconocido"
          schema:
            $ref: "#/definitions/Error"
  
    
definitions:
  Post:
    type: "object"
    required:
    - "id"
    - "userId"
    - "title"
    - "body"
    properties:
      id:
        type: "integer"
        format: "int64"
      userId:
        type: "integer"
        format: "int64"
      title:
        type: "string"
        example: "Titulo"
      body:
        type: "string"
        example: "Contenido del post"
        
  NewPost:
    type: "object"
    required:
    - "userId"
    - "title"
    - "body"
    properties:
      userId:
        type: "integer"
        format: "int64"
      title:
        type: "string"
        example: "Titulo"
      body:
        type: "string"
        example: "Contenido del post"
        
  EditPost:
    type: "object"
    properties:
      userId:
        type: "integer"
        format: "int64"
      title:
        type: "string"
        example: "Titulo"
      body:
        type: "string"
        example: "Contenido del post"
        
  Comment:
    type: "object"
    required:
    - "id"
    - "postId"
    - "email"
    - "name"
    - "body"
    properties:
      id:
        type: "integer"
        format: "int64"
      postId:
        type: "integer"
        format: "int64"
      email:
        type: "string"
        example: "email@domain.com"
      name:
        type: "string"
        example: "Nombre"
      body:
        type: "string"
        example: "Contenido del comentario"
        
  NewComment:
    type: "object"
    required:
    - "postId"
    - "email"
    - "name"
    - "body"
    properties:
      postId:
        type: "integer"
        format: "int64"
      email:
        type: "string"
        example: "email@domain.com"
      name:
        type: "string"
        example: "Nombre"
      body:
        type: "string"
        example: "Contenido del comentario"
        
  EditComment:
    type: "object"
    properties:
      postId:
        type: "integer"
        format: "int64"
      email:
        type: "string"
        example: "email@domain.com"
      name:
        type: "string"
        example: "Nombre"
      body:
        type: "string"
        example: "Contenido del comentario"
        
  Error:
    type: "object"
    required:
    - "ERROR"
    properties:
      ERROR:
        type: "string"
        example: "Error desconocido"
